name: Run tests and upload to docker hub WINDOWS
on: [push]
jobs:

  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.10"]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies on Ubuntu
      if: runner.os == 'Linux'
      run: |
        python -m pip install --upgrade pip
        pip install pytest Cython
        pip install torch==2.0.0 -f https://download.pytorch.org/whl/cpu
        pip install .
    
    - name: Install dependencies on Windows / MacOS
      if: runner.os == 'Windows' || runner.os == 'macOS'
      run: |
        python -m pip install --upgrade pip
        pip install pytest Cython
        pip install torch==2.0.0
        pip install .

    - name: Run test script
      run: python tests/tests_win.py
